# Generated by Django 6.0 on 2025-12-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload a profile picture (max 2MB)', null=True, upload_to='profile_pics/'),
        ),
    ]
