# Generated by Django 6.0 on 2026-01-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_email_verification_token_user_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
